--------------------------------------------------------
--  DDL for Procedure BATCH_POS_TABLE_DATA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "CRMDEV"."BATCH_POS_TABLE_DATA" 
IS 
BEGIN 
    -- ==========================================================================================
    -- Author        :   박동수
    -- Create date   :   2018-02-22
    -- Description   :   POS DB의 HQ_USER, STORE, L_NATION, 공통코드(00600), 공통코드(00605) 이관
    -- ==========================================================================================
    ---------------------------------------------- HQ_USER ----------------------------------------------
    BEGIN
      MERGE INTO HQ_USER A
      USING HQ_USER@HPOSDB B
      ON (A.COMP_CD = B.COMP_CD AND
          A.USER_ID = B.USER_ID)
      WHEN NOT MATCHED THEN
        INSERT ( 
          COMP_CD,USER_ID,USER_NM,PWD,PWD_CHG_YN,PWD_CHG_DT,BRAND_CD,DEPT_CD,TEAM_CD,POSITION_CD,USER_DIV,DUTY_CD,WEB_AUTH_CD,MST_ORG_CD,MNG_CARD_ID,TEL_NO,MOBILE_NO
          ,E_MAIL,ZIP_CD,ADDR1,ADDR2,NATION_CD,REGION_NO,LANGUAGE_TP,LOGIN_DTM,LOGIN_PERM_YN,LOGIN_FAIL_CNT,START_DT,USE_YN,ERP_USER_ID,INST_DT,INST_USER,UPD_DT,UPD_USER
        ) VALUES (
          B.COMP_CD,B.USER_ID,B.USER_NM,B.PWD,B.PWD_CHG_YN,B.PWD_CHG_DT,B.BRAND_CD,B.DEPT_CD,B.TEAM_CD,B.POSITION_CD,B.USER_DIV,B.DUTY_CD,B.WEB_AUTH_CD,B.MST_ORG_CD,B.MNG_CARD_ID,B.TEL_NO,B.MOBILE_NO
          ,B.E_MAIL,B.ZIP_CD,B.ADDR1,B.ADDR2,B.NATION_CD,B.REGION_NO,B.LANGUAGE_TP,B.LOGIN_DTM,B.LOGIN_PERM_YN,B.LOGIN_FAIL_CNT,B.START_DT,B.USE_YN,B.ERP_USER_ID,B.INST_DT,B.INST_USER,B.UPD_DT,B.UPD_USER
        )
      WHEN MATCHED THEN 
        UPDATE SET
          USER_NM = B.USER_NM, PWD = B.PWD, PWD_CHG_YN = B.PWD_CHG_YN, PWD_CHG_DT = B.PWD_CHG_DT, BRAND_CD = B.BRAND_CD, DEPT_CD = B.DEPT_CD
          ,TEAM_CD = B.TEAM_CD, POSITION_CD = B.POSITION_CD, USER_DIV = B.USER_DIV, DUTY_CD = B.DUTY_CD, WEB_AUTH_CD = B.WEB_AUTH_CD
          ,MST_ORG_CD = B.MST_ORG_CD, MNG_CARD_ID = B.MNG_CARD_ID, TEL_NO = B.TEL_NO, MOBILE_NO = B.MOBILE_NO, E_MAIL = B.E_MAIL
          ,ZIP_CD = B.ZIP_CD, ADDR1 = B.ADDR1, ADDR2 = B.ADDR2, NATION_CD = B.NATION_CD, REGION_NO = B.REGION_NO, LANGUAGE_TP = UPPER(B.LANGUAGE_TP)
          ,LOGIN_DTM = B.LOGIN_DTM, LOGIN_PERM_YN = B.LOGIN_PERM_YN, LOGIN_FAIL_CNT = B.LOGIN_FAIL_CNT, START_DT = B.START_DT, USE_YN = B.USE_YN
          ,ERP_USER_ID = B.ERP_USER_ID, UPD_DT = B.UPD_DT, UPD_USER = B.UPD_USER
        ;
    END;
    
    ---------------------------------------------- STORE ----------------------------------------------
    BEGIN
      MERGE INTO STORE A
      USING (SELECT * FROM STORE@HPOSDB WHERE STOR_TP IN ('10', '20')) B
      ON (A.COMP_CD = B.COMP_CD AND A.BRAND_CD = B.BRAND_CD AND A.STOR_CD = B.STOR_CD)
      WHEN NOT MATCHED THEN
        INSERT (
          COMP_CD,BRAND_CD,STOR_CD,REP_STOR_CD,ERP_STOR_CD,ERP_CC_CD,STOR_NM,STOR_TP,STOR_TG,DEPT_CD,TEAM_CD,BUSI_NO,SUB_BUSI_NO,BUSI_NM,BUSI_TP,BUSI_CT,ZIP_CD,ADDR1
          ,ADDR2,ADDR1_ENG,ADDR2_ENG,BILL_ADDR,TEL_NO,FAX,E_MAIL,DV_USER_ID,SV_USER_ID,CENTER_CD,SIDO_CD,REGION_CD,TRAD_AREA,APP_DIV,REST_AREA_TP,CONTRACT_NM,EXECUTE_NM
          ,EXECUTE_TEL,EXECUTE_HP,CONTRACT_DIV,OPEN_DT,CLOSE_DT,OFFER_TM,STOR_FORM,TABLE_NO,SEAT,SPACE,NATION_CD,CURRENCY_CD,REGION_NO,DSTN_COMP,ASIS_STOR_CD,COMM_YN
          ,INSHOP_YN,SELF_POS_YN,ERP_ITEM_GRP,ERP_SALE_GRP,ERP_SL_CD,ERP_BIZAREA,CONTRACT_DT,EXPIRATION_DT,USE_YN,INST_DT,INST_USER,UPD_DT,UPD_USER
        ) VALUES (
          B.COMP_CD,B.BRAND_CD,B.STOR_CD,B.REP_STOR_CD,B.ERP_STOR_CD,B.ERP_CC_CD,B.STOR_NM,B.STOR_TP,B.STOR_TG,B.DEPT_CD,B.TEAM_CD,B.BUSI_NO,B.SUB_BUSI_NO,B.BUSI_NM,B.BUSI_TP,B.BUSI_CT
          ,B.ZIP_CD,B.ADDR1,B.ADDR2,B.ADDR1_ENG,B.ADDR2_ENG,B.BILL_ADDR,B.TEL_NO,B.FAX,B.E_MAIL,B.DV_USER_ID,B.SV_USER_ID,B.CENTER_CD,B.SIDO_CD,B.REGION_CD,B.TRAD_AREA,B.APP_DIV,B.REST_AREA_TP
          ,B.CONTRACT_NM,B.EXECUTE_NM,B.EXECUTE_TEL,B.EXECUTE_HP,B.CONTRACT_DIV,B.OPEN_DT,B.CLOSE_DT,B.OFFER_TM,B.STOR_FORM,B.TABLE_NO,B.SEAT,B.SPACE,B.NATION_CD,B.CURRENCY_CD,B.REGION_NO
          ,B.DSTN_COMP,B.ASIS_STOR_CD,B.COMM_YN,B.INSHOP_YN,B.SELF_POS_YN,B.ERP_ITEM_GRP,B.ERP_SALE_GRP,B.ERP_SL_CD,B.ERP_BIZAREA,B.CONTRACT_DT,B.EXPIRATION_DT
          ,B.USE_YN,B.INST_DT,B.INST_USER,B.UPD_DT,B.UPD_USER
        ) 
      WHEN MATCHED THEN
        UPDATE SET
          REP_STOR_CD = B.REP_STOR_CD, ERP_STOR_CD = B.ERP_STOR_CD, ERP_CC_CD = B.ERP_CC_CD, STOR_NM = B.STOR_NM, STOR_TP = B.STOR_TP, STOR_TG = B.STOR_TG
          ,DEPT_CD = B.DEPT_CD, TEAM_CD = B.TEAM_CD, BUSI_NO = B.BUSI_NO, SUB_BUSI_NO = B.SUB_BUSI_NO, BUSI_NM = B.BUSI_NM, BUSI_TP = B.BUSI_TP, BUSI_CT = B.BUSI_CT
          ,ZIP_CD = B.ZIP_CD, ADDR1 = B.ADDR1, ADDR2 = B.ADDR2, ADDR1_ENG = B.ADDR1_ENG, ADDR2_ENG = B.ADDR2_ENG, BILL_ADDR = B.BILL_ADDR, TEL_NO = B.TEL_NO
          ,FAX = B.FAX, E_MAIL = B.E_MAIL, DV_USER_ID = B.DV_USER_ID, SV_USER_ID = B.SV_USER_ID, CENTER_CD = B.CENTER_CD, SIDO_CD = B.SIDO_CD, REGION_CD = B.REGION_CD
          ,TRAD_AREA = B.TRAD_AREA, APP_DIV = B.APP_DIV, REST_AREA_TP = B.REST_AREA_TP, CONTRACT_NM = B.CONTRACT_NM, EXECUTE_NM = B.EXECUTE_NM, EXECUTE_TEL = B.EXECUTE_TEL
          ,EXECUTE_HP = B.EXECUTE_HP, CONTRACT_DIV = B.CONTRACT_DIV, OPEN_DT = B.OPEN_DT, CLOSE_DT = B.CLOSE_DT, OFFER_TM = B.OFFER_TM, STOR_FORM = B.STOR_FORM
          ,TABLE_NO = B.TABLE_NO, SEAT = B.SEAT, SPACE = B.SPACE, NATION_CD = B.NATION_CD, CURRENCY_CD = B.CURRENCY_CD, REGION_NO = B.REGION_NO, DSTN_COMP = B.DSTN_COMP
          ,ASIS_STOR_CD = B.ASIS_STOR_CD, COMM_YN = B.COMM_YN, INSHOP_YN = B.INSHOP_YN, SELF_POS_YN = B.SELF_POS_YN, ERP_ITEM_GRP = B.ERP_ITEM_GRP
          ,ERP_SALE_GRP = B.ERP_SALE_GRP, ERP_SL_CD = B.ERP_SL_CD, ERP_BIZAREA = B.ERP_BIZAREA, CONTRACT_DT = B.CONTRACT_DT, EXPIRATION_DT = B.EXPIRATION_DT
          ,USE_YN = B.USE_YN, INST_DT = B.INST_DT, INST_USER = B.INST_USER, UPD_DT = B.UPD_DT, UPD_USER = B.UPD_USER
      ;
    END;
    ---------------------------------------------- L_NATION ----------------------------------------------
    BEGIN
      MERGE INTO L_NATION A
      USING L_NATION@HPOSDB B
      ON (A.NATION_CD = B.NATION_CD)
      WHEN NOT MATCHED THEN
        INSERT (
          NATION_CD, NATION_NM, NATION_NO, CONTINENT_CD, CURRENCY_CD, UTC_CD, SMT_NO, SORT_ORDER, USE_YN, INST_DT, INST_USER, UPD_DT, UPD_USER
        ) VALUES (
          B.NATION_CD, B.NATION_NM, B.NATION_NO, B.CONTINENT_CD, B.CURRENCY_CD, B.UTC_CD, B.SMT_NO, B.SORT_ORDER, B.USE_YN, B.INST_DT, B.INST_USER, B.UPD_DT, B.UPD_USER
        )
      WHEN MATCHED THEN
        UPDATE SET
          NATION_NM = B.NATION_NM, NATION_NO = B.NATION_NO, CONTINENT_CD = B.CONTINENT_CD, CURRENCY_CD = B.CURRENCY_CD, UTC_CD = B.UTC_CD, SMT_NO = B.SMT_NO
          , SORT_ORDER = B.SORT_ORDER, USE_YN = B.USE_YN, INST_DT = B.INST_DT, INST_USER = B.INST_USER, UPD_DT = B.UPD_DT, UPD_USER = B.UPD_USER
      ;
    END;
    
    ---------------------------------------------- 공통코드(00600), 공통코드(00605) 이관 ----------------------------------------------
    BEGIN
      MERGE INTO COMMON A
      USING (SELECT * FROM COMMON@HPOSDB WHERE CODE_TP IN ('00600', '00605')) B
      ON (A.CODE_TP = B.CODE_TP AND A.CODE_CD = B.CODE_CD)
      WHEN NOT MATCHED THEN
        INSERT (
          CODE_TP,CODE_CD,CODE_NM,BRAND_CD,SORT_SEQ,ACC_CD,VAL_D1,VAL_D2,VAL_C1,VAL_C2
          ,VAL_N1,VAL_N2,REMARKS,USE_YN,INST_DT,INST_USER,UPD_DT,UPD_USER,POS_IF_YN,VAL_C3,VAL_C4,VAL_C5
        ) VALUES (
          B.CODE_TP,B.CODE_CD,B.CODE_NM,B.BRAND_CD,B.SORT_SEQ,B.ACC_CD,B.VAL_D1,B.VAL_D2,B.VAL_C1,B.VAL_C2
          ,B.VAL_N1,B.VAL_N2,B.REMARKS,B.USE_YN,B.INST_DT,B.INST_USER,B.UPD_DT,B.UPD_USER,B.POS_IF_YN,B.VAL_C3,B.VAL_C4,B.VAL_C5
        )
      WHEN MATCHED THEN
        UPDATE SET
          CODE_NM = B.CODE_NM,BRAND_CD = B.BRAND_CD,SORT_SEQ = B.SORT_SEQ
          ,ACC_CD = B.ACC_CD,VAL_D1 = B.VAL_D1,VAL_D2 = B.VAL_D2,VAL_C1 = B.VAL_C1,VAL_C2 = B.VAL_C2
          ,VAL_N1 = B.VAL_N1,VAL_N2 = B.VAL_N2,REMARKS = B.REMARKS,USE_YN = B.USE_YN,INST_DT = B.INST_DT,INST_USER = B.INST_USER
          ,UPD_DT = B.UPD_DT,UPD_USER = B.UPD_USER,POS_IF_YN = B.POS_IF_YN,VAL_C3 = B.VAL_C3,VAL_C4 = B.VAL_C4,VAL_C5 = B.VAL_C5
      ;
    END;
END BATCH_POS_TABLE_DATA;

/
