--------------------------------------------------------
--  DDL for Procedure HQ_USER_SELECT
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "CRMDEV"."HQ_USER_SELECT" (
    P_USER_ID IN  HQ_USER.USER_ID%TYPE,
    O_CURSOR  OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN O_CURSOR FOR
    SELECT
      USER_ID, USER_NM, PWD, BRAND_CD, DEPT_CD, TEAM_CD, POSITION_CD, DUTY_CD, HIGHER_USER_ID, PGM_PTN, MST_ORG_CD, ITEM_CONF_YN,
      STOR_CONF_YN, ADMIN_YN, COMP_TEL_NO, TEL_NO, E_MAIL, STOR_VISIT_YN, MNG_CARD_ID, ZIP_CD, ADDR, ADDR2, LANGUAGE_TP, ERP_INF_YN,
      CERTIFY_YN, PWD_CHG_YN, PWD_CHG_DT, ORG_CD, LOGIN_DTM, USE_YN, INST_DT, INST_USER, UPD_DT, UPD_USER, WEB_AUTH_CD
      COMP_CD, GW_USER_ID, MOBILE_NO, USER_DIV
    FROM HQ_USER
    WHERE (P_USER_ID IS NULL OR USER_ID = P_USER_ID)
    ;
END HQ_USER_SELECT;

/
