--------------------------------------------------------
--  DDL for Procedure PROMOTION_ACC_MEM_SELECT
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "CRMDEV"."PROMOTION_ACC_MEM_SELECT" (
    N_START_DT  IN  VARCHAR2,
    N_END_DT    IN  VARCHAR2,
    N_STOR_CD   IN  VARCHAR2,
    O_CURSOR    OUT SYS_REFCURSOR
) AS 
BEGIN  

    -- ==========================================================================================
    -- Author		:	박동수
    -- Create date	:	2018-03-28
    -- Description	:	프로모션 정산조회 멤버쉽실적 상세현황 조회
    -- ==========================================================================================
    OPEN O_CURSOR FOR
    SELECT A.*
           , (A.USE_PT*-1) AS SETTLE_AMT 
    FROM (
      SELECT
        ROW_NUMBER() OVER (ORDER BY A.SALE_DT ASC) AS RNUM
        ,A.SALE_DT
        ,A.STOR_CD
        ,A.BILL_NO
        ,DECRYPT(A.CUST_NM) AS CUST_NM
        ,DECRYPT(CARD_ID) AS CARD_ID
        ,(SELECT STOR_NM FROM STORE WHERE STOR_CD = A.STOR_CD AND BRAND_CD = '100') AS STOR_NM
        ,(SELECT H.USER_NM FROM STORE S, HQ_USER H WHERE S.STOR_CD = A.STOR_CD AND S.BRAND_CD = '100' AND S.SV_USER_ID = H.USER_ID) AS STOR_SC
        ,(SELECT CODE_NM FROM STORE S, COMMON C WHERE S.STOR_CD = A.STOR_CD AND S.BRAND_CD = '100' AND C.CODE_TP = '00565' AND C.CODE_CD = S.STOR_TP) AS STOR_TP
        ,(SELECT CODE_NM FROM STORE S, COMMON C WHERE S.STOR_CD = A.STOR_CD AND S.BRAND_CD = '100' AND C.CODE_TP = '00605' AND C.CODE_CD = S.TEAM_CD) AS TEAM_NM
        ,A.SALE_AMT AS SALE_AMT
        ,A.DC_AMT + A.ENR_AMT AS DC_AMT
        ,A.GRD_I_AMT + A.GRD_O_AMT AS GRD_AMT
        ,(SELECT SUM(SAV_MLG) FROM C_CUST_CROWN WHERE USE_DT = A.SALE_DT AND STOR_CD = A.STOR_CD AND POS_NO = A.POS_NO AND BILL_NO = A.BILL_NO) AS SAV_MLG
        ,(SELECT SUM(USE_PT) FROM C_CARD_SAV_HIS WHERE USE_DT = A.SALE_DT AND STOR_CD = A.STOR_CD AND POS_NO = A.POS_NO AND BILL_NO = A.BILL_NO) AS USE_PT
      FROM SALE_HD A
      WHERE A.COMP_CD = '016'
      AND A.BRAND_CD = '100'
      AND A.SALE_DT >= REPLACE(N_START_DT, '-', '')
      AND A.SALE_DT <= REPLACE(N_END_DT, '-', '')
      AND NVL(A.CUST_ID, 'ISNULL') != 'ISNULL'
      AND (N_STOR_CD IS NULL OR A.STOR_CD = N_STOR_CD)
    )A
    ORDER BY RNUM DESC
    ;
    
--    OPEN O_CURSOR FOR
--    SELECT A.* FROM (
--      SELECT
--        ROW_NUMBER() OVER (ORDER BY A.SALE_DT ASC) AS RNUM
--        ,A.SALE_DT
--        ,A.STOR_CD
--        ,A.BILL_NO
--        --,(SELECT DECRYPT(CUST_NM) FROM C_CUST WHERE CUST_ID = A.CUST_ID) AS CUST_NM
--        --,(SELECT DECRYPT(CARD_ID) FROM C_CARD WHERE CUST_ID = A.CUST_ID AND REP_CARD_YN = 'Y' AND USE_YN = 'Y') AS CARD_ID
--        --,(SELECT STOR_NM FROM STORE WHERE STOR_CD = A.STOR_CD AND BRAND_CD = '100') AS STOR_NM
--        --,(SELECT GET_COMMON_CODE_NM('00565', STOR_TP) FROM STORE WHERE STOR_CD = A.STOR_CD AND BRAND_CD = '100') AS STOR_TP
--        --,(SELECT H.USER_NM FROM STORE S, HQ_USER H WHERE S.STOR_CD = A.STOR_CD AND S.BRAND_CD = '100' AND S.SV_USER_ID = H.USER_ID) AS STOR_SC
--        --,(SELECT GET_COMMON_CODE_NM('00605', TEAM_CD) FROM STORE WHERE STOR_CD = A.STOR_CD AND BRAND_CD = '100') AS TEAM_NM
--        ,A.SALE_AMT AS SALE_AMT
--        ,A.DC_AMT + A.ENR_AMT AS DC_AMT
--        ,A.GRD_I_AMT + A.GRD_O_AMT AS GRD_AMT
--        ,(SELECT SUM(SAV_MLG) FROM C_CUST_CROWN WHERE USE_DT = A.SALE_DT AND STOR_CD = A.STOR_CD AND POS_NO = A.POS_NO AND BILL_NO = A.BILL_NO) AS SAV_MLG
--        ,(SELECT SUM(USE_PT) FROM C_CARD_SAV_HIS WHERE USE_DT = A.SALE_DT AND STOR_CD = A.STOR_CD AND POS_NO = A.POS_NO AND BILL_NO = A.BILL_NO) AS USE_PT
--      FROM SALE_HD A
--      WHERE A.COMP_CD = '016'
--      AND A.SALE_DT >= REPLACE(N_START_DT, '-', '')
--      AND A.SALE_DT <= REPLACE(N_END_DT, '-', '')
--      AND (N_STOR_CD IS NULL OR A.STOR_CD = N_STOR_CD)
--    )A
--    ;
    
END PROMOTION_ACC_MEM_SELECT;

/
