--------------------------------------------------------
--  DDL for Procedure SP_DEL_TRAN
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "CRMDEV"."SP_DEL_TRAN" 
(
  psv_comp_cd     IN   STRING, -- Company Code
  psv_brand_cd    IN   STRING, -- 브랜드코드
  psv_stor_cd     IN   STRING, -- 점포코드
  psv_fr_dt       IN   STRING, -- 일자
  psv_to_dt       IN   STRING, -- 일자
  psr_return_cd   OUT  NUMBER, -- 메세지코드
  psr_msg         OUT  STRING  -- 메세지
) 
/*======================================================================*/
/*  Project Name    :  EnZIN POS 시스템                                 */
/*  Procedure Name  :  SP_DEL_TRAN                                      */
/*  Author Co.      :  (주)진코퍼레이션                                 */
/*  Author          :                                                   */
/*  ALTER  Date     :  2013/01/25                                       */
/*  Modify Date     :                                                   */
/*  Remark          :  집계 TABLE  삭제                                 */
/*                  :                                                   */
/*                  :                                                   */
/*  Table           :                                                   */
/*======================================================================*/
IS
  liv_msg_code    NUMBER(9) := 0;
  lsv_msg_text    VARCHAR2(200);

  ERR_HANDLER     EXCEPTION;
BEGIN
    liv_msg_code    := 1;
    lsv_msg_text    := '정상처리가 완료 되었습니다.';

    DELETE FROM APPERR_LOG             WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SALE_DT    BETWEEN PSV_FR_DT AND PSV_TO_DT ;
    DELETE FROM ATTENDANCE             WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND ATTD_DT    BETWEEN PSV_FR_DT AND PSV_TO_DT ;
    DELETE FROM CARD_LOG               WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SALE_DT    BETWEEN PSV_FR_DT AND PSV_TO_DT ;
    DELETE FROM CASH_LOG               WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SALE_DT    BETWEEN PSV_FR_DT AND PSV_TO_DT ;
    DELETE FROM CHECK_LOG              WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SALE_DT    BETWEEN PSV_FR_DT AND PSV_TO_DT ;
    DELETE FROM C_CUST_TRAN_LIST       WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SALE_DT    BETWEEN PSV_FR_DT AND PSV_TO_DT ; -- 선불/후불 거래내역
    DELETE FROM DC_LOG                 WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SALE_DT    BETWEEN PSV_FR_DT AND PSV_TO_DT ;
    DELETE FROM DEL_DT                 WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SALE_DT    BETWEEN PSV_FR_DT AND PSV_TO_DT ;
    -- 매장이동 감안
    DELETE FROM DSTOCK                 WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND PRC_DT     BETWEEN PSV_FR_DT AND PSV_TO_DT ; -- 일수불
    DELETE FROM DSTOCK_ADJ             WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND ADJ_DT     BETWEEN PSV_FR_DT AND PSV_TO_DT ; -- 일수불(타계정)
    -- GIFT_STOCK 감안 안함
    DELETE FROM MOBILE_LOG             WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SALE_DT    BETWEEN PSV_FR_DT AND PSV_TO_DT ;
    DELETE FROM MOVE_STORE             WHERE COMP_CD = PSV_COMP_CD AND OUT_BRAND_CD = PSV_BRAND_CD AND OUT_STOR_CD = PSV_STOR_CD AND MV_DT  BETWEEN PSV_FR_DT AND PSV_TO_DT ; -- 매장이동
    DELETE FROM MSTOCK                 WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND PRC_YM     BETWEEN SUBSTR(PSV_FR_DT, 1, 6) AND SUBSTR(PSV_TO_DT, 1, 6) ;       -- 월수불
    DELETE FROM NOTI_USER              WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND WRITE_DT   BETWEEN PSV_FR_DT AND PSV_TO_DT ; -- 점포전달노트 수신자
    DELETE FROM NOTIFICATION           WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND WRITE_DT   BETWEEN PSV_FR_DT AND PSV_TO_DT ;
    DELETE FROM POINT_LOG              WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SALE_DT    BETWEEN PSV_FR_DT AND PSV_TO_DT ;
    DELETE FROM POINT_SUM              WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SALE_DT    BETWEEN PSV_FR_DT AND PSV_TO_DT ;
    DELETE FROM POS_SPEC               WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND YMD        BETWEEN PSV_FR_DT AND PSV_TO_DT ; -- POS 시스템 사양정보
    DELETE FROM POS_TRAN_UPLOAD        WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SEND_DT    BETWEEN PSV_FR_DT AND PSV_TO_DT ; -- POS TR 업로드
    DELETE FROM PRODUCT_DT             WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND PRD_DT     BETWEEN PSV_FR_DT AND PSV_TO_DT ; -- 생산 D
    DELETE FROM PRODUCT_HD             WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND PRD_DT     BETWEEN PSV_FR_DT AND PSV_TO_DT ;
    DELETE FROM REPRINT_LOG            WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SALE_DT    BETWEEN PSV_FR_DT AND PSV_TO_DT ;
    DELETE FROM SALE_ATM               WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SALE_DT    BETWEEN PSV_FR_DT AND PSV_TO_DT ;
    DELETE FROM SALE_CDR               WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SALE_DT    BETWEEN PSV_FR_DT AND PSV_TO_DT ;
    DELETE FROM SALE_CL                WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SALE_DT    BETWEEN PSV_FR_DT AND PSV_TO_DT ;
    DELETE FROM SALE_CT                WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SALE_DT    BETWEEN PSV_FR_DT AND PSV_TO_DT ;
    DELETE FROM SALE_DT                WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SALE_DT    BETWEEN PSV_FR_DT AND PSV_TO_DT ;
    DELETE FROM SALE_HD                WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SALE_DT    BETWEEN PSV_FR_DT AND PSV_TO_DT ;
    DELETE FROM SALE_JDA               WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SALE_DT    BETWEEN PSV_FR_DT AND PSV_TO_DT ; -- 점포별 금액대별 일집계
    DELETE FROM SALE_JDC               WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SALE_DT    BETWEEN PSV_FR_DT AND PSV_TO_DT ;
    DELETE FROM SALE_JDCT              WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SALE_DT    BETWEEN PSV_FR_DT AND PSV_TO_DT ;
    DELETE FROM SALE_JDD               WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SALE_DT    BETWEEN PSV_FR_DT AND PSV_TO_DT ;
    DELETE FROM SALE_JDF               WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SALE_DT    BETWEEN PSV_FR_DT AND PSV_TO_DT ;
    DELETE FROM SALE_JDG               WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SALE_DT    BETWEEN PSV_FR_DT AND PSV_TO_DT ;
    DELETE FROM SALE_JDH               WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SALE_DT    BETWEEN PSV_FR_DT AND PSV_TO_DT ;
    DELETE FROM SALE_JDI               WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SALE_DT    BETWEEN PSV_FR_DT AND PSV_TO_DT ;
    DELETE FROM SALE_JDM               WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SALE_DT    BETWEEN PSV_FR_DT AND PSV_TO_DT ;
    DELETE FROM SALE_JDO               WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SALE_DT    BETWEEN PSV_FR_DT AND PSV_TO_DT ;
    DELETE FROM SALE_JDP               WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SALE_DT    BETWEEN PSV_FR_DT AND PSV_TO_DT ;
    DELETE FROM SALE_JDP_GC            WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SALE_DT    BETWEEN PSV_FR_DT AND PSV_TO_DT ;
    DELETE FROM SALE_JDPR              WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SALE_DT    BETWEEN PSV_FR_DT AND PSV_TO_DT ;
    DELETE FROM SALE_JDS               WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SALE_DT    BETWEEN PSV_FR_DT AND PSV_TO_DT ;
    DELETE FROM SALE_JDW               WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SALE_DT    BETWEEN PSV_FR_DT AND PSV_TO_DT ;
    DELETE FROM SALE_JIM               WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SALE_DT    BETWEEN PSV_FR_DT AND PSV_TO_DT ;
    DELETE FROM SALE_JMI               WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SALE_YM    BETWEEN SUBSTR(PSV_FR_DT, 1, 6) AND SUBSTR(PSV_TO_DT, 1, 6) ;
    DELETE FROM SALE_JMM               WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SALE_YM    BETWEEN SUBSTR(PSV_FR_DT, 1, 6) AND SUBSTR(PSV_TO_DT, 1, 6) ;
    DELETE FROM SALE_JMO               WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SALE_YM    BETWEEN SUBSTR(PSV_FR_DT, 1, 6) AND SUBSTR(PSV_TO_DT, 1, 6) ;
    DELETE FROM SALE_JTM               WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SALE_DT    BETWEEN PSV_FR_DT AND PSV_TO_DT ;
    DELETE FROM SALE_JTO               WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SALE_DT    BETWEEN PSV_FR_DT AND PSV_TO_DT ;
    DELETE FROM SALE_JTS               WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SALE_DT    BETWEEN PSV_FR_DT AND PSV_TO_DT ;
    DELETE FROM SALE_SDC               WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SALE_DT    BETWEEN PSV_FR_DT AND PSV_TO_DT ;
    DELETE FROM SALE_ST                WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SALE_DT    BETWEEN PSV_FR_DT AND PSV_TO_DT ;
    DELETE FROM SALE_ST_MC             WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SALE_DT    BETWEEN PSV_FR_DT AND PSV_TO_DT ;
    DELETE FROM STORE_ETC_AMT          WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND PRC_DT     BETWEEN PSV_FR_DT AND PSV_TO_DT ;
    DELETE FROM STORE_OC               WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND YMD        BETWEEN PSV_FR_DT AND PSV_TO_DT ;
    DELETE FROM SURV_STOCK_DT          WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SURV_DT    BETWEEN PSV_FR_DT AND PSV_TO_DT ; -- 재고실사 D
    DELETE FROM SURV_STOCK_HD          WHERE COMP_CD = PSV_COMP_CD AND BRAND_CD = PSV_BRAND_CD AND STOR_CD = PSV_STOR_CD AND SURV_DT    BETWEEN PSV_FR_DT AND PSV_TO_DT ; -- 재고실사 H


    psr_return_cd := liv_msg_code;
    psr_msg       := lsv_msg_text;
EXCEPTION
  WHEN ERR_HANDLER THEN
       psr_return_cd := liv_msg_code;
       psr_msg       := lsv_msg_text;
  WHEN OTHERS THEN
       psr_return_cd := liv_msg_code;
       psr_msg       := lsv_msg_text;
END;

/
