--------------------------------------------------------
--  DDL for Procedure SP_DEL_COMPANY
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "CRMDEV"."SP_DEL_COMPANY" 
(
  PSV_COMP_CD     IN   STRING, -- Company Code
  PSR_RETURN_CD   OUT  NUMBER, -- 메세지코드
  PSR_MSG         OUT  STRING  -- 메세지
) 
/*======================================================================*/
/*  Project Name    :  EnZIN POS 시스템                                 */
/*  Procedure Name  :  SP_DEL_COMPANY                                   */
/*  Author Co.      :  (주)진코퍼레이션                                 */
/*  Author          :                                                   */
/*  ALTER  Date     :  2014/05/23                                       */
/*  Modify Date     :                                                   */
/*  Remark          :  회사데이터  삭제                                 */
/*                  :                                                   */
/*                  :                                                   */
/*  Table           :                                                   */
/*======================================================================*/
IS
  liv_msg_code    NUMBER(9) := 0;
  lsv_msg_text    VARCHAR2(200);

  ERR_HANDLER     EXCEPTION;
BEGIN
    liv_msg_code    := 1;
    lsv_msg_text    := '정상처리가 완료 되었습니다.';

    DELETE FROM ACC_HD                    WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ACC_MST                   WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM APPERR_LOG                WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ATTD_CONFIRM              WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ATTD_IF                   WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ATTD_PATTERN              WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ATTD_PATTERN_COMPANY      WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ATTD_PATTERN_STORE        WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ATTD_PAY_MAEIL            WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ATTD_SCHEDULE             WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ATTD_SCHEDULE_DT          WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ATTD_SCHEDULE_HD          WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ATTENDANCE                WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM BARCODE                   WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM BEST_ITEM                 WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM BILL_MSG_HQ               WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM BILL_MSG_STOR             WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM BRAND                     WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM BRAND_TIME                WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM BUNDLE_DT                 WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM BUNDLE_HD                 WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM BUTTON_INFO               WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM CARD                      WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM CARDMB_PREFIX             WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM CASH_LOG                  WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM CATID                     WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM CATID_LOG                 WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM CHECK_LOG                 WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM COMMON                    WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM COMPANY                   WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM C_CUST_TRAN_LIST          WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM DC                        WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM DC_GIFT                   WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM DC_ITEM                   WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM DC_ITEM_GRP               WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM DC_LOG                    WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM DC_STORE                  WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM DC_WEEK                   WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM DEL_DT                    WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM DSTOCK                    WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM DSTOCK_ADJ                WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ERR_LOG_IF_POS            WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM GIFT_CODE_BRAND           WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM GIFT_CODE_MST             WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM GIFT_ERR_LOG              WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM GIFT_IN_DT                WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM GIFT_IN_HD                WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM GIFT_LOG                  WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM GIFT_MST                  WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM GIFT_MST_LOG              WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM GIFT_SALE_DT              WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM GIFT_SALE_HD              WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM GIFT_SALE_ST              WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM GIFT_STOCK                WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM GIFT_STOCK_STORE          WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM GIFT_SVR_LOG              WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM GIFT_UNSOLD               WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM HQ_USER                   WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM INSPECT                   WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ITEM                      WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ITEM_CHAIN                WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ITEM_CHAIN_HIS            WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ITEM_CHAIN_RCP            WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ITEM_CHAIN_REV            WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ITEM_CHAIN_STD            WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ITEM_CLASS                WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ITEM_EXT_GRP              WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ITEM_FLAG                 WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ITEM_INFO                 WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ITEM_KITCHEN              WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ITEM_L_CLASS              WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ITEM_M_CLASS              WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ITEM_OPTION_RULE          WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ITEM_S_CLASS              WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ITEM_SET                  WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ITEM_SET_GRP              WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ITEM_STORE                WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM JAVA_SCJ_L                WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM JAVA_SCJ_M                WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM LANG_COMMON               WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM LANG_ITEM                 WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM LANG_STORE                WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM LANG_TABLE                WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM LANGUAGE                  WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM MASTER_MNG                WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM MASTER_ORG                WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM MESSAGE_MST               WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM MOBILE_LOG                WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM MOVE_STORE                WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM MSTOCK                    WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM MULTI_ANALYSIS            WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM NOTI_USER                 WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM NOTIFICATION              WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM OC_CENTER_TM              WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM OC_EXC_BRAND              WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM OC_EXC_CENTER_ITEM        WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM OC_EXC_GRP                WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM OC_EXC_ITEM               WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM OC_EXC_PERIOD             WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM OC_EXC_SEQ                WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM OC_EXC_STORE              WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM OC_ORD_GRP                WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM OC_ORD_GRP_BRAND          WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM OC_ORD_GRP_DDAY           WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM OC_ORD_GRP_ITEM           WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM OC_ORD_GRP_SEQ            WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM OC_ORD_GRP_STORE          WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM OC_ORD_GRP_TM             WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM OC_STORE_DDAY             WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM OC_STORE_ITEM_QTY         WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM OC_STORE_TM               WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM OPEN_STORE                WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM OPTION_GRP                WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM OPTION_ITEM               WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ORD_GOAL_RESULT           WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ORD_SCR_CHK               WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ORD_SCR_CHK_LOG           WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ORDER_COLLECT             WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ORDER_COLLECT_INFO        WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ORDER_COLLECT_ITEM        WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ORDER_COLLECT_ITEM_DLV    WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ORDER_COLLECT_ITEM_LIMIT  WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ORDER_COLLECT_ITEM_NM     WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ORDER_COLLECT_STORE       WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ORDER_DT                  WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ORDER_DTV                 WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ORDER_HD                  WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ORDER_HDV                 WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ORDER_LOG                 WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ORDER_MSG                 WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ORDER_TMP                 WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ORDER_TMP_LOG             WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ORDRTN_DT                 WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM ORDRTN_HD                 WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM PL_ACC_MST                WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM PL_ACC_MST_LINK           WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM PL_DO_003                 WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM PL_DO_CLASS_003           WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM PL_DO_CLASS_LINK_003      WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM PL_DO_HIS_003             WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM PL_GOAL_DD                WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM PL_GOAL_YM                WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM PL_GOAL_YM_HQ             WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM PL_MCOST_003              WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM PL_MCOST_CLASS_003        WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM POINT_LOG                 WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM POINT_SUM                 WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM POS_PGM_AUTH              WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM POS_SPEC                  WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM POS_TRAN_UPLOAD           WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM PRODUCT_DT                WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM PRODUCT_HD                WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM PROFIT_GOAL               WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM RECIPE_BRAND              WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM RECIPE_BRAND_FOOD         WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM RECIPE_BRAND_FOOD_REV     WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM REF_ITEM                  WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM REF_STORE                 WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM REGION                    WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM REJECT_DT                 WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM REJECT_EVENT              WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM REJECT_EVENT_ITEM         WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM REJECT_EVENT_STORE        WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM REJECT_FIXED              WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM REJECT_FIXED_ITEM         WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM REJECT_FIXED_STORE        WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM REJECT_HD                 WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM REJECT_SYSTEM             WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM REJECT_SYSTEM_ITEM        WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM REJECT_SYSTEM_MONTH       WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM REPRINT_LOG               WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SALE_ATM                  WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SALE_CDR                  WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SALE_CL                   WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SALE_CT                   WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SALE_DT                   WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SALE_GOAL_DAY             WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SALE_GOAL_YM              WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SALE_GOAL_YMD             WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SALE_HD                   WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SALE_JDA                  WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SALE_JDC                  WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SALE_JDCT                 WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SALE_JDD                  WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SALE_JDF                  WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SALE_JDG                  WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SALE_JDH                  WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SALE_JDI                  WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SALE_JDM                  WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SALE_JDO                  WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SALE_JDP                  WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SALE_JDP_GC               WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SALE_JDPR                 WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SALE_JDS                  WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SALE_JDW                  WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SALE_JIM                  WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SALE_JMI                  WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SALE_JMM                  WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SALE_JMO                  WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SALE_JTM                  WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SALE_JTO                  WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SALE_JTS                  WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SALE_SDC                  WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SALE_ST                   WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SALE_ST_MC                WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SET_GRP_ITEM              WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SET_GRP_ITEM_STORE        WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SET_GRP_RULE              WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SET_GRP_RULE_STORE        WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SET_RULE                  WHERE COMP_CD = PSV_COMP_CD;
    --DELETE FROM SET_RULE_STORE            WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM STORE                     WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM STORE_ATTD_PAY            WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM STORE_ETC_AMT             WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM STORE_FLAG                WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM STORE_HOLIDAY             WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM STORE_ITEM_PRT            WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM STORE_ITEM_PRT_MULTI      WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM STORE_OC                  WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM STORE_PAY                 WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM STORE_PROD_ITEM           WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM STORE_PRT                 WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM STORE_PURCHASE            WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM STORE_SETUP               WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM STORE_USER                WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SUB_ITEM                  WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SUB_STORE_ITEM            WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SUB_STORE_TOUCH_UI        WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SUB_TOUCH_UI              WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SURV_STOCK_DT             WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM SURV_STOCK_HD             WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM TOUCH_STORE_UI            WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM TOUCH_UI                  WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM UNI_SCHD                  WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM USER_AUTH                 WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM USER_DC_CARD              WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM USER_DC_CARD_RULE         WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM USER_DC_SALE_JYT          WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM VAN                       WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM VAN_MSG                   WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM W_BOARD_ATT               WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM W_BOARD_AUTH_NEW          WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM W_BOARD_CTG               WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM W_BOARD_LST               WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM W_BOARD_MGR               WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM W_BOARD_NOTI_AUTH         WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM W_BOARD_OPN               WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM W_BOARD_RCV               WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM W_BOARD_RDH               WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM W_BOARD_TXT               WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM W_BOARD_TXT_KEEP          WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM W_MENU                    WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM W_MENU_FAVORITE           WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM W_MENU_GROUP              WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM W_MENU_MOBILE             WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM W_MENU_STOR_TP            WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM W_MENU_STOR_TP_MOBILE     WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM W_MENU_STORE_USER         WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM W_MENU_STORE_USER_MOBILE  WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM W_MENU_USER               WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM W_MENU_USER_MOBILE        WHERE COMP_CD = PSV_COMP_CD;
    DELETE FROM WORK_UNIT                 WHERE COMP_CD = PSV_COMP_CD;

    psr_return_cd := liv_msg_code;
    psr_msg       := lsv_msg_text;
EXCEPTION
  WHEN ERR_HANDLER THEN
       psr_return_cd := liv_msg_code;
       psr_msg       := lsv_msg_text;
  WHEN OTHERS THEN
       psr_return_cd := liv_msg_code;
       psr_msg       := lsv_msg_text;
END;

/
