CREATE OR REPLACE PACKAGE      PKG_CURSOR AS
  TYPE     REF_CUR IS  REF CURSOR;
  TYPE     TR_INTEGER  IS TABLE OF PLS_INTEGER      INDEX BY BINARY_INTEGER;
  TYPE     TR_STRINGA  IS TABLE OF VARCHAR2(20)     INDEX BY BINARY_INTEGER;
  TYPE     TR_STRINGB  IS TABLE OF VARCHAR2(50)     INDEX BY BINARY_INTEGER;
  TYPE     TR_STRINGC  IS TABLE OF VARCHAR2(100)    INDEX BY BINARY_INTEGER;
  TYPE     TR_STRINGD  IS TABLE OF VARCHAR2(2000)   INDEX BY BINARY_INTEGER;
  TYPE     TR_NUMBER   IS TABLE OF NUMBER           INDEX BY BINARY_INTEGER;
  TYPE     PARA_CD_T   IS VARRAY(2)  OF VARCHAR2(5)   ;
END PKG_CURSOR;

/
