--------------------------------------------------------
--  DDL for Function FN_INSERT_TEMP_DATA
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "CRMDEV"."FN_INSERT_TEMP_DATA" RETURN VARCHAR2 IS
    CURSOR CUR_1 IS
        SELECT TNAME, CNAME, COLTYPE, COLNO,
               MAX(COLNO) OVER(PARTITION BY TNAME) MAX_COLNO
        FROM   COL
        WHERE  TNAME IN
        ('C_CARD_USE_HIS','C_COUPON_CUST','C_COUPON_CUST_GIFT','C_COUPON_CUST_GIFT_HIS','C_COUPON_CUST_HIS','C_COUPON_ITEM_GRP','C_COUPON_MST','C_CUST_BIT','C_CUST_BRAND','C_CUST_FBD',
        'C_CUST_MSG','C_CUST_TRAN_LIST','C_MAIL_CONTENT','C_MAIL_CONTENT_LOG','C_MAIL_SEND_LOG','C_MMS_SEND_LOG','C_SMS_SEND_LOG','DSTOCK_DO','GIFT_ERR_LOG','GIFT_LOG','GIFT_STOCK_STORE',
        'GIFT_SVR_LOG','INSPECT','ITEM_B2B_DC_HIS','ITEM_INFO','ITEM_KITCHEN','ITEM_OPTION_RULE','JAVA_SCJ_L','JAVA_SCJ_M','LANGUAGE','MILEAGE_LOG','MOBILE_LOG','MULTI_ANALYSIS','NOTIFICATION',
        'NOTI_USER','OC_CENTER_TM','OC_EXC_BRAND','OC_EXC_CENTER_ITEM','OC_EXC_GRP','OC_EXC_ITEM','OC_EXC_PERIOD','OC_EXC_SEQ','OC_EXC_STORE','OC_ORD_GRP','OC_ORD_GRP_BRAND','OC_ORD_GRP_DDAY','OC_ORD_GRP_ITEM',
        'OC_ORD_GRP_SEQ','OC_ORD_GRP_STORE','OC_ORD_GRP_TM','OC_STORE_DDAY','OC_STORE_ITEM_QTY','OC_STORE_PROP','OC_STORE_PROP_A','OC_STORE_TM','OPEN_STORE','ORDER_COLLECT','ORDER_COLLECT_INFO','ORDER_COLLECT_ITEM',
        'ORDER_COLLECT_ITEM_DLV','ORDER_COLLECT_ITEM_LIMIT','ORDER_COLLECT_ITEM_NM','ORDER_COLLECT_STORE','ORDER_DT','ORDER_HD','ORDER_LOG','ORDER_MSG','ORDER_TMP','ORDER_TMP_LOG','ORDRTN_DT','ORDRTN_HD','ORD_GOAL_RESULT','ORD_SCR_CHK',
        'ORD_SCR_CHK_LOG','PL_ACC_MST_LINK','POINT_SUM','POS_TRAN_UPLOAD','PROFIT_GOAL','REF_ITEM','REF_STORE','REJECT_DT','REJECT_EVENT','REJECT_EVENT_ITEM','REJECT_EVENT_STORE','REJECT_FIXED','REJECT_FIXED_ITEM',
        'REJECT_FIXED_STORE','REJECT_HD','REJECT_SYSTEM','REJECT_SYSTEM_ITEM','REJECT_SYSTEM_MONTH','SALE_DESC','SALE_GOAL_YM','SALE_GOAL_YMD','SALE_JDG','SALE_JDW','SALE_ST_MC','SET_GRP_ITEM_STORE','STORE_ITEM_VENDOR',
        'STORE_PAY','STORE_PURCHASE','SUB_ITEM','SUB_TOUCH_UI','TOAD_PLAN_SQL','UNI_SCHD','USER_DC_CARD','USER_DC_CARD_RULE','USER_DC_SALE_JYT','WORK_UNIT',
        'W_BOARD_ATT','W_BOARD_CTG','W_BOARD_MGR','W_BOARD_NOTI_AUTH','W_BOARD_OPN','W_BOARD_RCV','W_BOARD_RDH','W_BOARD_TXT','W_BOARD_TXT_KEEP','W_MENU_FAVORITE','W_MENU_STORE','W_MENU_STORE_USER_MOBILE')
        ORDER BY TNAME, COLNO;

        vINSERTSQL VARCHAR2(2000) := NULL;
        vINSERTVAL VARCHAR2(2000) := NULL;
        vRECCNT     NUMBER := 0;
BEGIN
    FOR MYREC IN CUR_1 LOOP
        EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM '||MYREC.TNAME INTO vRECCNT;

        IF vRECCNT = 0 AND MYREC.COLTYPE != 'DATE' THEN
            IF MYREC.COLNO = 1 THEN
                vINSERTSQL := ' INSERT INTO '||MYREC.TNAME||' ( '||MYREC.CNAME;
                vINSERTVAL := ' VALUES (1';
            ELSE
                vINSERTSQL := vINSERTSQL||' , '||MYREC.CNAME;
                vINSERTVAL := vINSERTVAL||' ,1';
            END IF;

            IF MYREC.COLNO = MYREC.MAX_COLNO THEN
                vINSERTSQL := vINSERTSQL||' )';
                vINSERTVAL := vINSERTVAL||' )';

                EXECUTE IMMEDIATE vINSERTSQL||vINSERTVAL;

                COMMIT;
            END IF;
        END IF;
    END LOOP;   

   RETURN '0';
EXCEPTION
     WHEN OTHERS THEN
       ROLLBACK;
       RETURN SQLERRM;
END FN_INSERT_TEMP_DATA;

/
