--------------------------------------------------------
--  DDL for Function GET_SUBPART_TS_9I
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "CRMDEV"."GET_SUBPART_TS_9I" 
  (V_OWNER VARCHAR2, V_TNAME VARCHAR2, V_PNAME VARCHAR2, V_PART_COUNT NUMBER)
RETURN VARCHAR2 IS
     TBS_STRING   VARCHAR2(4000) := '';
  BEGIN

 FOR CUR_SQL IN (SELECT SUBPARTITION_POSITION, TABLESPACE_NAME
	               FROM   SYS.ALL_TAB_SUBPARTITIONS
	               WHERE  TABLE_OWNER     = UPPER(V_OWNER)
                 AND    TABLE_NAME      = UPPER(V_TNAME)
                 AND    PARTITION_NAME  = UPPER(V_PNAME)
                 ORDER BY SUBPARTITION_POSITION
	              ) LOOP

    IF (CUR_SQL.SUBPARTITION_POSITION = 1) 
    THEN  TBS_STRING   := ' SUBPARTITIONS '||V_PART_COUNT||CHR(10)||' STORE IN (';
    END IF;

    TBS_STRING   := TBS_STRING||CUR_SQL.TABLESPACE_NAME;

    IF (V_PART_COUNT = CUR_SQL.SUBPARTITION_POSITION) 
    THEN  TBS_STRING   := TBS_STRING||')';
    ELSE  TBS_STRING   := TBS_STRING||',';
    END IF;  

 END LOOP;

 RETURN TBS_STRING;
END;

/
