--------------------------------------------------------
--  DDL for Function GET_PART_HIGH_VALUE
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "CRMDEV"."GET_PART_HIGH_VALUE" 
  ( V_OWNER VARCHAR2, V_NAME VARCHAR2, V_PARTITION_NAME VARCHAR2,V_SW VARCHAR2 )
RETURN VARCHAR2 IS
     LONG_CHAR    VARCHAR2(4000);
  BEGIN
     IF V_SW = 'T' THEN  
	   SELECT HIGH_VALUE
	   INTO   LONG_CHAR
	   FROM   SYS.ALL_TAB_PARTITIONS
       WHERE  TABLE_OWNER    = UPPER(V_OWNER)
       AND    TABLE_NAME     = UPPER(V_NAME) 
	   AND    PARTITION_NAME = UPPER(V_PARTITION_NAME);

	   SELECT DECODE(PARTITIONING_TYPE,'HASH',NULL,'LIST',' VALUES (' || LONG_CHAR|| ')',
	          'RANGE',' VALUES LESS THAN (' ||  LONG_CHAR|| ')')
	   INTO  LONG_CHAR
	   FROM  SYS.ALL_PART_TABLES
	   WHERE OWNER      = UPPER(V_OWNER)
       AND   TABLE_NAME = UPPER(V_NAME) ;

	 ELSE 
	   SELECT HIGH_VALUE
	   INTO   LONG_CHAR
	   FROM   SYS.ALL_IND_PARTITIONS
       WHERE  INDEX_OWNER    = UPPER(V_OWNER)
       AND    INDEX_NAME     = UPPER(V_NAME) 
	   AND    PARTITION_NAME = UPPER(V_PARTITION_NAME);
	 END IF;

     RETURN LONG_CHAR ;
END;

/
